import { GlitchPreset } from '@/types/glitch';

export const glitchPresets: GlitchPreset[] = [
  {
    id: 'cyberpunk-text',
    name: 'Cyberpunk Split',
    description: 'Classic RGB split glitch effect',
    category: 'text',
    config: {
      effectName: 'Cyberpunk Split',
      duration: 1.5,
      loop: true,
      reverse: false,
      quality: 'high',
      shapes: ['rectangle'],
      shaderModules: ['rgbSplit', 'noise'],
      renderMode: 'image',
      params: {
        noiseIntensity: 0.7,
        splitDistance: 15,
        colorShift: 0.8,
      },
    },
  },
  {
    id: 'glitch-blocks',
    name: 'Glitch Blocks',
    description: 'Blocky digital distortion effect',
    category: 'shapes',
    config: {
      effectName: 'Glitch Blocks',
      duration: 2.0,
      loop: true,
      reverse: false,
      quality: 'medium',
      shapes: ['rectangle'],
      shaderModules: ['glitchBlocks', 'scanlines'],
      renderMode: 'image',
      params: {
        blockSize: 40,
        scanlineOpacity: 0.4,
        distortionAmount: 0.6,
      },
    },
  },
  {
    id: 'chromatic-wave',
    name: 'Chromatic Wave',
    description: 'Smooth chromatic aberration waves',
    category: 'artistic',
    config: {
      effectName: 'Chromatic Wave',
      duration: 3.0,
      loop: true,
      reverse: true,
      quality: 'high',
      shapes: ['circle'],
      shaderModules: ['rgbSplit', 'noise'],
      renderMode: 'image',
      params: {
        splitDistance: 8,
        noiseIntensity: 0.3,
      },
    },
  },
  {
    id: 'pixel-storm',
    name: 'Pixel Storm',
    description: 'Intense pixelation with RGB distortion',
    category: 'advanced',
    config: {
      effectName: 'Pixel Storm',
      duration: 1.0,
      loop: true,
      reverse: false,
      quality: 'medium',
      shapes: ['rectangle'],
      shaderModules: ['pixelate', 'rgbSplit', 'noise'],
      renderMode: 'image',
      params: {
        pixelSize: 12,
        splitDistance: 10,
        noiseIntensity: 0.9,
      },
    },
  },
  {
    id: 'scanline-retro',
    name: 'Scanline Retro',
    description: 'Old CRT monitor effect with scanlines',
    category: 'artistic',
    config: {
      effectName: 'Scanline Retro',
      duration: 2.5,
      loop: true,
      reverse: false,
      quality: 'high',
      shapes: ['rectangle'],
      shaderModules: ['scanlines', 'chromaticAberration'],
      renderMode: 'image',
      params: {
        scanlineOpacity: 0.6,
        aberrationStrength: 0.4,
      },
    },
  },
  {
    id: 'vhs-dream',
    name: 'VHS Dream',
    description: 'Nostalgic VHS tape distortion effect',
    category: 'artistic',
    config: {
      effectName: 'VHS Dream',
      duration: 3.5,
      loop: true,
      reverse: false,
      quality: 'medium',
      shapes: ['rectangle'],
      shaderModules: ['vhsDistortion', 'scanlines', 'noise'],
      renderMode: 'image',
      params: {
        vhsIntensity: 0.7,
        scanlineOpacity: 0.5,
        noiseIntensity: 0.4,
      },
    },
  },
  {
    id: 'data-corruption',
    name: 'Data Corruption',
    description: 'Intense datamosh effect with displacement',
    category: 'advanced',
    config: {
      effectName: 'Data Corruption',
      duration: 1.8,
      loop: true,
      reverse: false,
      quality: 'high',
      shapes: ['rectangle'],
      shaderModules: ['datamosh', 'displacement', 'rgbSplit'],
      renderMode: 'image',
      params: {
        datamoshAmount: 0.8,
        displacementStrength: 0.6,
        splitDistance: 8,
      },
    },
  },
  {
    id: 'neon-distortion',
    name: 'Neon Distortion',
    description: 'Heavy color shift with RGB split',
    category: 'artistic',
    config: {
      effectName: 'Neon Distortion',
      duration: 2.2,
      loop: true,
      reverse: false,
      quality: 'high',
      shapes: ['rectangle'],
      shaderModules: ['rgbSplit'],
      renderMode: 'image',
      params: {
        splitDistance: 20,
        colorShift: 0.9,
        noiseIntensity: 0.2,
      },
    },
  },
  {
    id: 'minimal-glitch',
    name: 'Minimal Glitch',
    description: 'Subtle scanline effect',
    category: 'text',
    config: {
      effectName: 'Minimal Glitch',
      duration: 3.0,
      loop: true,
      reverse: false,
      quality: 'medium',
      shapes: ['rectangle'],
      shaderModules: ['scanlines'],
      renderMode: 'image',
      params: {
        scanlineOpacity: 0.5,
        noiseIntensity: 0.1,
      },
    },
  },
];
